export const categoriesSeed = ['Policies','Reports','Finance','Human Resources','IT','Legal','Administration','Procurement','Training','Projects'].map((name,i)=>({id:`CAT-${String(i+1).padStart(3,'0')}`,name,description:`${name} documents and reference materials`,status:'Active'}));
export const departmentsSeed = ['Administration','Finance','Human Resources','Information Technology','Operations','Procurement','Legal','Customer Service'].map((name,i)=>({id:`DEP-${String(i+1).padStart(3,'0')}`,code:['ADM','FIN','HR','IT','OPS','PRO','LEG','CS'][i],name,manager:['Amara Niyonzima','Daniel Mutesi','Grace Uwimana','Eric Habimana','Alice Mukamana'][i%5],status:'Active'}));
const users=['Amara Niyonzima','Daniel Mutesi','Grace Uwimana','Eric Habimana','Alice Mukamana','Jean-Pierre Kayitesi','Claudine Uwera','Patrick Nshimiyimana','Diane Ingabire','Samuel Nkurunziza','Beata Mukamana','Emmanuel Rukundo','Olivia Tuyishime','David Bizimana','Aline Nyirahabimana','Robert Mugisha','Chantal Umutesi','Fabrice Ndayisaba','Mireille Uwase','Claude Rwamagana'];
const types=[['PDF','.pdf','application/pdf'],['Word','.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['Excel','.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],['PowerPoint','.pptx','application/vnd.openxmlformats-officedocument.presentationml.presentation'],['Text','.txt','text/plain'],['Image','.png','image/png'],['CSV','.csv','text/csv']];
const titles=['Annual operating plan','Supplier agreement','Quarterly performance review','Staff handbook','Information security policy','Budget forecast','Client onboarding guide','Project status update','Audit findings summary','Training attendance register','Records retention schedule','Service delivery report','Procurement request','Risk assessment','Meeting minutes','Payroll reconciliation','Network access procedure','Customer feedback analysis','Travel policy','Strategic roadmap'];
const tags=[['Management','2026'],['Confidential','Review'],['Annual','Finance'],['Operations','Approved'],['Planning','2026'],['Internal','Reference'],['Quarterly','Management'],['Compliance','Policy']];
export function makeDocuments(){
 const now=new Date(); return Array.from({length:108},(_,i)=>{const [fileType,extension,mimeType]=types[i%types.length], title=titles[i%titles.length], category=categoriesSeed[(i*7+Math.floor(i/5))%10].name, department=departmentsSeed[(i*5+Math.floor(i/8))%8].name, daysAgo=(i*13)%410, date=new Date(now.getTime()-daysAgo*86400000), status=i<24?(i%2===0?'Deleted':'Archived'):i%13===0?'Deleted':i%11===0?'Archived':'Active';const fileName=`${title.toLowerCase().replace(/[^a-z0-9]+/g,'_')}_${2026-i%3}${extension}`;return{id:`doc-${String(i+1).padStart(4,'0')}`,documentNumber:`DOC-${now.getFullYear()}-${String(i+1).padStart(4,'0')}`,fileName,title,description:`${title} prepared for the ${department} team. Maintained as part of the organization’s ${category.toLowerCase()} records.`,fileType,extension,mimeType,size:((i*7919)%6200000)+145000,category,department,uploadedBy:users[i%users.length],uploadDate:date.toISOString(),lastModified:new Date(date.getTime()+((i%7)*86400000)).toISOString(),lastAccessed:new Date(now.getTime()-((i*3)%35)*86400000).toISOString(),version:`${1+i%3}.${i%10}`,status,favorite:i%5===0||i%9===0,downloadCount:(i*7)%43,openCount:2+(i*11)%97,tags:tags[i%tags.length],remarks:i%4===0?'Reviewed by department lead':'',history:[]};});
}
export const formatSize=(n=0)=>n<1024*1024?`${(n/1024).toFixed(0)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
export const formatDate=(v)=>v?new Intl.DateTimeFormat('en',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—';
export const readStore=(key,fallback)=>{try{const v=localStorage.getItem(key);if(!v)return fallback;const parsed=JSON.parse(v);if(key==='documents'&&(!Array.isArray(parsed)||parsed.some(d=>!d||typeof d!=='object'||typeof d.id!=='string'||typeof d.fileName!=='string'||!Array.isArray(d.tags))))return fallback;if(key==='documentCategories'&&(!Array.isArray(parsed)||parsed.some(x=>!x||typeof x.name!=='string')))return fallback;if(key==='departments'&&(!Array.isArray(parsed)||parsed.some(x=>!x||typeof x.name!=='string')))return fallback;if(key==='documentHistory'&&(!Array.isArray(parsed)||parsed.some(x=>!x||typeof x!=='object')))return fallback;if(fallback&&typeof fallback==='object'&&!Array.isArray(fallback)&&(!parsed||typeof parsed!=='object'||Array.isArray(parsed)))return fallback;if(Array.isArray(fallback)&&!Array.isArray(parsed))return fallback;if(fallback===null&&key!=='documents')return fallback;return parsed}catch{return fallback}};
